---
- name: Ensure ~/.shell exists
  ansible.builtin.file:
    path: ~/.shell
    state: directory

- name: Install forgit
  ansible.builtin.git:
    clone: true
    repo: https://github.com/wfxr/forgit.git
    dest: ~/.shell/forgit

- name: Clone NeoVim config
  ansible.builtin.git:
    clone: true
    repo: git@github.com:nhudson/vimrc.git
    dest: ~/.config/nvim
