---
# Sets HostName.

- name: Find out the current macOS HostName value.
  command: "scutil --get HostName"
  register: "current_hostname"
  changed_when: false
  # If the HostName is not set--this is often true, `scutil --get HostName`
  # returns an error code (d'oh!) with the empty string stdout that we _want_.
  failed_when: false

- name: Set macOS HostName, even when it's an empty string.
  command: "scutil --set HostName '{{ osx_hostname }}'"
  become: true
  when: >
    osx_hostname is defined
    or (
      current_hostname.stdout is defined
      and current_hostname.stdout != osx_hostname
    )
  notify: clear dns cache

- name: Set macOS LocalHostName.
  command: "scutil --set LocalHostName '{{ osx_hostname }}'"
  when:
    - "osx_hostname != current_hostname.stdout"
  become: true
  notify: clear dns cache

- name: Set macOS ComputerName.
  command: "scutil --set ComputerName '{{ osx_hostname }}'"
  when:
    - "osx_hostname != current_hostname.stdout"
  become: true
  notify: clear dns cache
